// Code generated by protoc-gen-go. DO NOT EDIT.
// source: session_establishment.proto

package v1

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RequestType int32

const (
	RequestType_REQUEST_TYPE_INITIAL   RequestType = 0
	RequestType_REQUEST_TYPE_EXISTING  RequestType = 1
	RequestType_REQUEST_TYPE_HANDOVER  RequestType = 3
	RequestType_REQUEST_TYPE_EMERGENCY RequestType = 4
)

var RequestType_name = map[int32]string{
	0: "REQUEST_TYPE_INITIAL",
	1: "REQUEST_TYPE_EXISTING",
	3: "REQUEST_TYPE_HANDOVER",
	4: "REQUEST_TYPE_EMERGENCY",
}

var RequestType_value = map[string]int32{
	"REQUEST_TYPE_INITIAL":   0,
	"REQUEST_TYPE_EXISTING":  1,
	"REQUEST_TYPE_HANDOVER":  3,
	"REQUEST_TYPE_EMERGENCY": 4,
}

func (x RequestType) String() string {
	return proto.EnumName(RequestType_name, int32(x))
}

func (RequestType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_40aa8c4aba089cbd, []int{0}
}

type CNTunnelInfo struct {
	TunnelId             int32    `protobuf:"varint,1,opt,name=tunnelId,proto3" json:"tunnelId,omitempty"`
	Ipv4Address          string   `protobuf:"bytes,2,opt,name=ipv4address,proto3" json:"ipv4address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CNTunnelInfo) Reset()         { *m = CNTunnelInfo{} }
func (m *CNTunnelInfo) String() string { return proto.CompactTextString(m) }
func (*CNTunnelInfo) ProtoMessage()    {}
func (*CNTunnelInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_40aa8c4aba089cbd, []int{0}
}

func (m *CNTunnelInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CNTunnelInfo.Unmarshal(m, b)
}
func (m *CNTunnelInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CNTunnelInfo.Marshal(b, m, deterministic)
}
func (m *CNTunnelInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CNTunnelInfo.Merge(m, src)
}
func (m *CNTunnelInfo) XXX_Size() int {
	return xxx_messageInfo_CNTunnelInfo.Size(m)
}
func (m *CNTunnelInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_CNTunnelInfo.DiscardUnknown(m)
}

var xxx_messageInfo_CNTunnelInfo proto.InternalMessageInfo

func (m *CNTunnelInfo) GetTunnelId() int32 {
	if m != nil {
		return m.TunnelId
	}
	return 0
}

func (m *CNTunnelInfo) GetIpv4Address() string {
	if m != nil {
		return m.Ipv4Address
	}
	return ""
}

type SessionEstablishmentRequest struct {
	Supi                 string      `protobuf:"bytes,1,opt,name=supi,proto3" json:"supi,omitempty"`
	PduSessionId         int64       `protobuf:"varint,2,opt,name=pduSessionId,proto3" json:"pduSessionId,omitempty"`
	Dnn                  string      `protobuf:"bytes,3,opt,name=dnn,proto3" json:"dnn,omitempty"`
	RequestType          RequestType `protobuf:"varint,4,opt,name=requestType,proto3,enum=v1.RequestType" json:"requestType,omitempty"`
	DirectionType        string      `protobuf:"bytes,5,opt,name=directionType,proto3" json:"directionType,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *SessionEstablishmentRequest) Reset()         { *m = SessionEstablishmentRequest{} }
func (m *SessionEstablishmentRequest) String() string { return proto.CompactTextString(m) }
func (*SessionEstablishmentRequest) ProtoMessage()    {}
func (*SessionEstablishmentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_40aa8c4aba089cbd, []int{1}
}

func (m *SessionEstablishmentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionEstablishmentRequest.Unmarshal(m, b)
}
func (m *SessionEstablishmentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionEstablishmentRequest.Marshal(b, m, deterministic)
}
func (m *SessionEstablishmentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionEstablishmentRequest.Merge(m, src)
}
func (m *SessionEstablishmentRequest) XXX_Size() int {
	return xxx_messageInfo_SessionEstablishmentRequest.Size(m)
}
func (m *SessionEstablishmentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionEstablishmentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SessionEstablishmentRequest proto.InternalMessageInfo

func (m *SessionEstablishmentRequest) GetSupi() string {
	if m != nil {
		return m.Supi
	}
	return ""
}

func (m *SessionEstablishmentRequest) GetPduSessionId() int64 {
	if m != nil {
		return m.PduSessionId
	}
	return 0
}

func (m *SessionEstablishmentRequest) GetDnn() string {
	if m != nil {
		return m.Dnn
	}
	return ""
}

func (m *SessionEstablishmentRequest) GetRequestType() RequestType {
	if m != nil {
		return m.RequestType
	}
	return RequestType_REQUEST_TYPE_INITIAL
}

func (m *SessionEstablishmentRequest) GetDirectionType() string {
	if m != nil {
		return m.DirectionType
	}
	return ""
}

type SessionEstablishmentResponse struct {
	Supi                 string        `protobuf:"bytes,1,opt,name=supi,proto3" json:"supi,omitempty"`
	CnTunnelInfo         *CNTunnelInfo `protobuf:"bytes,2,opt,name=cnTunnelInfo,proto3" json:"cnTunnelInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *SessionEstablishmentResponse) Reset()         { *m = SessionEstablishmentResponse{} }
func (m *SessionEstablishmentResponse) String() string { return proto.CompactTextString(m) }
func (*SessionEstablishmentResponse) ProtoMessage()    {}
func (*SessionEstablishmentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_40aa8c4aba089cbd, []int{2}
}

func (m *SessionEstablishmentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionEstablishmentResponse.Unmarshal(m, b)
}
func (m *SessionEstablishmentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionEstablishmentResponse.Marshal(b, m, deterministic)
}
func (m *SessionEstablishmentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionEstablishmentResponse.Merge(m, src)
}
func (m *SessionEstablishmentResponse) XXX_Size() int {
	return xxx_messageInfo_SessionEstablishmentResponse.Size(m)
}
func (m *SessionEstablishmentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionEstablishmentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SessionEstablishmentResponse proto.InternalMessageInfo

func (m *SessionEstablishmentResponse) GetSupi() string {
	if m != nil {
		return m.Supi
	}
	return ""
}

func (m *SessionEstablishmentResponse) GetCnTunnelInfo() *CNTunnelInfo {
	if m != nil {
		return m.CnTunnelInfo
	}
	return nil
}

type SessionUpdateRequest struct {
	Supi                 string   `protobuf:"bytes,1,opt,name=supi,proto3" json:"supi,omitempty"`
	Dnn                  string   `protobuf:"bytes,2,opt,name=dnn,proto3" json:"dnn,omitempty"`
	SmcontextId          string   `protobuf:"bytes,3,opt,name=smcontext_id,json=smcontextId,proto3" json:"smcontext_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SessionUpdateRequest) Reset()         { *m = SessionUpdateRequest{} }
func (m *SessionUpdateRequest) String() string { return proto.CompactTextString(m) }
func (*SessionUpdateRequest) ProtoMessage()    {}
func (*SessionUpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_40aa8c4aba089cbd, []int{3}
}

func (m *SessionUpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionUpdateRequest.Unmarshal(m, b)
}
func (m *SessionUpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionUpdateRequest.Marshal(b, m, deterministic)
}
func (m *SessionUpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionUpdateRequest.Merge(m, src)
}
func (m *SessionUpdateRequest) XXX_Size() int {
	return xxx_messageInfo_SessionUpdateRequest.Size(m)
}
func (m *SessionUpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionUpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SessionUpdateRequest proto.InternalMessageInfo

func (m *SessionUpdateRequest) GetSupi() string {
	if m != nil {
		return m.Supi
	}
	return ""
}

func (m *SessionUpdateRequest) GetDnn() string {
	if m != nil {
		return m.Dnn
	}
	return ""
}

func (m *SessionUpdateRequest) GetSmcontextId() string {
	if m != nil {
		return m.SmcontextId
	}
	return ""
}

func init() {
	proto.RegisterEnum("v1.RequestType", RequestType_name, RequestType_value)
	proto.RegisterType((*CNTunnelInfo)(nil), "v1.CNTunnelInfo")
	proto.RegisterType((*SessionEstablishmentRequest)(nil), "v1.SessionEstablishmentRequest")
	proto.RegisterType((*SessionEstablishmentResponse)(nil), "v1.SessionEstablishmentResponse")
	proto.RegisterType((*SessionUpdateRequest)(nil), "v1.SessionUpdateRequest")
}

func init() { proto.RegisterFile("session_establishment.proto", fileDescriptor_40aa8c4aba089cbd) }

var fileDescriptor_40aa8c4aba089cbd = []byte{
	// 400 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0xd1, 0x6e, 0xd3, 0x30,
	0x14, 0x86, 0x49, 0xdb, 0x4d, 0xec, 0xa4, 0x40, 0x64, 0x0d, 0x14, 0x3a, 0x24, 0x42, 0xc4, 0x45,
	0xc5, 0x45, 0xa5, 0x96, 0xbd, 0xc0, 0x54, 0xac, 0x61, 0x31, 0x02, 0x38, 0x19, 0x62, 0x57, 0x51,
	0x16, 0x1f, 0x34, 0xa3, 0xcd, 0x09, 0xb1, 0x13, 0xb1, 0xb7, 0xe3, 0xd1, 0x50, 0x9d, 0x68, 0x4d,
	0x44, 0xb7, 0x3b, 0xfb, 0xf7, 0xf9, 0xff, 0x93, 0xf3, 0xe5, 0xc0, 0x91, 0x46, 0xad, 0x65, 0xa1,
	0x52, 0xd4, 0x26, 0xbb, 0xbc, 0x96, 0xfa, 0xea, 0x06, 0x95, 0x59, 0x94, 0x55, 0x61, 0x0a, 0x32,
	0x6a, 0x96, 0xe1, 0x19, 0x4c, 0xd7, 0x51, 0x52, 0x2b, 0x85, 0xd7, 0x4c, 0xfd, 0x2c, 0xc8, 0x0c,
	0x1e, 0x9b, 0xf6, 0x26, 0x7c, 0x27, 0x70, 0xe6, 0x7b, 0xfc, 0xee, 0x4e, 0x02, 0x70, 0x65, 0xd9,
	0x1c, 0x67, 0x42, 0x54, 0xa8, 0xb5, 0x3f, 0x0a, 0x9c, 0xf9, 0x01, 0xef, 0x4b, 0xe1, 0x5f, 0x07,
	0x8e, 0xe2, 0xb6, 0x23, 0xed, 0x37, 0xe4, 0xf8, 0xbb, 0x46, 0x6d, 0x08, 0x81, 0x89, 0xae, 0x4b,
	0x69, 0x93, 0x0f, 0xb8, 0x3d, 0x93, 0x10, 0xa6, 0xa5, 0xa8, 0x3b, 0x17, 0x13, 0x36, 0x76, 0xcc,
	0x07, 0x1a, 0xf1, 0x60, 0x2c, 0x94, 0xf2, 0xc7, 0xd6, 0xb6, 0x39, 0x92, 0x25, 0xb8, 0x55, 0x1b,
	0x9a, 0xdc, 0x96, 0xe8, 0x4f, 0x02, 0x67, 0xfe, 0x74, 0xf5, 0x6c, 0xd1, 0x2c, 0x17, 0x7c, 0x2b,
	0xf3, 0x7e, 0x0d, 0x79, 0x0b, 0x4f, 0x84, 0xac, 0x30, 0x37, 0xb2, 0x50, 0xd6, 0xb4, 0x67, 0xe3,
	0x86, 0x62, 0x78, 0x05, 0xaf, 0x76, 0x4f, 0xa0, 0xcb, 0x42, 0x69, 0xdc, 0x39, 0xc2, 0x31, 0x4c,
	0x73, 0xb5, 0x85, 0x68, 0x47, 0x70, 0x57, 0xde, 0xe6, 0x6b, 0xfa, 0x70, 0xf9, 0xa0, 0x2a, 0x4c,
	0xe1, 0xb0, 0xeb, 0x74, 0x5e, 0x8a, 0xcc, 0xe0, 0x43, 0x90, 0x3a, 0x00, 0xa3, 0x2d, 0x80, 0x37,
	0x30, 0xd5, 0x37, 0x79, 0xa1, 0x0c, 0xfe, 0x31, 0xa9, 0x14, 0x1d, 0x1b, 0xf7, 0x4e, 0x63, 0xe2,
	0xdd, 0x2d, 0xb8, 0x3d, 0x18, 0xc4, 0x87, 0x43, 0x4e, 0xbf, 0x9d, 0xd3, 0x38, 0x49, 0x93, 0x8b,
	0xaf, 0x34, 0x65, 0x11, 0x4b, 0xd8, 0xc9, 0x99, 0xf7, 0x88, 0xbc, 0x84, 0xe7, 0x83, 0x17, 0xfa,
	0x83, 0xc5, 0x09, 0x8b, 0x4e, 0x3d, 0xe7, 0xbf, 0xa7, 0x8f, 0x27, 0xd1, 0x87, 0x2f, 0xdf, 0x29,
	0xf7, 0xc6, 0x64, 0x06, 0x2f, 0x86, 0xae, 0xcf, 0x94, 0x9f, 0xd2, 0x68, 0x7d, 0xe1, 0x4d, 0x56,
	0xbf, 0x76, 0xef, 0x41, 0x8c, 0x55, 0x23, 0x73, 0x24, 0x9f, 0x60, 0x7f, 0x5d, 0x61, 0x66, 0x90,
	0xbc, 0xde, 0x40, 0x7a, 0x60, 0x65, 0x66, 0xc1, 0xfd, 0x05, 0xed, 0x1f, 0xb9, 0xdc, 0xb7, 0xdb,
	0xfc, 0xfe, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xb9, 0xe8, 0xe5, 0xb8, 0xec, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SessionEstablishmentServiceClient is the client API for SessionEstablishmentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SessionEstablishmentServiceClient interface {
	Create(ctx context.Context, in *SessionEstablishmentRequest, opts ...grpc.CallOption) (*SessionEstablishmentResponse, error)
}

type sessionEstablishmentServiceClient struct {
	cc *grpc.ClientConn
}

func NewSessionEstablishmentServiceClient(cc *grpc.ClientConn) SessionEstablishmentServiceClient {
	return &sessionEstablishmentServiceClient{cc}
}

func (c *sessionEstablishmentServiceClient) Create(ctx context.Context, in *SessionEstablishmentRequest, opts ...grpc.CallOption) (*SessionEstablishmentResponse, error) {
	out := new(SessionEstablishmentResponse)
	err := c.cc.Invoke(ctx, "/v1.SessionEstablishmentService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SessionEstablishmentServiceServer is the server API for SessionEstablishmentService service.
type SessionEstablishmentServiceServer interface {
	Create(context.Context, *SessionEstablishmentRequest) (*SessionEstablishmentResponse, error)
}

// UnimplementedSessionEstablishmentServiceServer can be embedded to have forward compatible implementations.
type UnimplementedSessionEstablishmentServiceServer struct {
}

func (*UnimplementedSessionEstablishmentServiceServer) Create(ctx context.Context, req *SessionEstablishmentRequest) (*SessionEstablishmentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}

func RegisterSessionEstablishmentServiceServer(s *grpc.Server, srv SessionEstablishmentServiceServer) {
	s.RegisterService(&_SessionEstablishmentService_serviceDesc, srv)
}

func _SessionEstablishmentService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionEstablishmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionEstablishmentServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.SessionEstablishmentService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionEstablishmentServiceServer).Create(ctx, req.(*SessionEstablishmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SessionEstablishmentService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.SessionEstablishmentService",
	HandlerType: (*SessionEstablishmentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _SessionEstablishmentService_Create_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "session_establishment.proto",
}
